# Generated by Django 2.1 on 2018-09-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_author', models.CharField(max_length=100)),
                ('book_pages', models.IntegerField()),
                ('book_category', models.CharField(max_length=100)),
                ('book_front', models.CharField(max_length=500)),
                ('book_pdf', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app1.Users'),
        ),
    ]
